---
- name: "Set configset list"
  find:
    paths: "{{ solr_configset_path }}"
    file_type: directory
  register: configset_output
  become: True
  when: auto_populate_configset_list

- name: "Populate configset list"
  set_fact:
    configset_list: "{{ configset_output.files | map(attribute='path') | list | \
      map('replace', solr_configset_path + '/', '') | list }}"
  when: auto_populate_configset_list

- name: "Get config files list contained replication handler"
  find:
    paths: "{{ configset_list | \
      map('regex_replace', '(.*)', solr_configset_path + '/\\1/conf') | list }}"
    patterns: "solrconfig.xml"
    contains: "(.*)requestHandler(.*)replication(.*)solr.ReplicationHandler(.*)"
  register: true_configset_xml_list
  become: True

- name: "Configure solr node as slave"
  blockinfile:
    dest: "{{ item.path }}"
    insertafter: '<requestHandler name="/replication" class="solr.ReplicationHandler" >'
    marker: " <!-- {mark} solr ansible custom block --> "
    block: |
      <lst name="slave">
      <str name="masterUrl">{{ solr_master_generated_url }}</str>
      <str name="pollInterval">00:00:60</str>
      </lst>
    state: present
  become: True
  loop: "{{ true_configset_xml_list.files }}"
  notify:
    - "restart solr linux"

- name: "Force all notified handlers"
  meta: flush_handlers
