---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-master
  vars:
    solr_change_default_password: False
    solr_master_defined_host: solr-master.example.com
